### ISSUE TITLE
dl_matrix3du_t

### ISSUE THREAD

**Issue by clotaireFrance** [dagnall53/TrackCamera#1]
Hello

I get this error:

'dl_matrix3du_t' was not declared in this scope

i had to comment 
//#include "dl_lib.h"
because the file was not found

**Comment by dagnall53** [comment]
Hi, thanks for this. 
I had forgotten about the Track Camera.. !
I now use the WIO-Camera  https://gitlab.com/rocrail/wio  as it is better integrated into RocRail.
